### ISSUE TITLE
Is wget needed?

### ISSUE THREAD

**Issue by blankoworld** [Lukc/pkgxx#13]
Thursday I met a problem while Alpine Linux have busybox wget command.

Is wget needed as a dependencies? If yes is it possible to add it in the README.md?

Thanks in advance.

**Comment by Lukc** [comment]
`wget` is currently needed, because we don’t use a HTTP download library directly.
However, only the `-O` option of `wget` is being used at the moment, making busybox’s implementation compatible.

I’m not sure if it’ll stay like that in the future, as we may want to implement partial downloads and resuming interrupted downloads.
Doing so with lua-http (or similar) may (or may not) be complicated, but using a few additional `wget` (or `curl`) switches is not.

7c7517c4b119d61a6962b6ba51532bf1256ad82e mentioned the requirement on a `wget` implementation in the README.
